#!/usr/bin/perl

# Copyright (c) 2005, INRIA.  
#               All rights reserved.
# 		Geoffroy Vallee <gvallee@irisa.fr>
#
# $Id$
# 
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
 
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#   This is the oscar installation program.  It must be called with
#   one argument which is the installation network device

use strict;
use Cwd qw(chdir cwd);

use lib cwd() . "/lib";
use vars qw($VERSION);
use OSCAR::Logger;
use OSCAR::Distro;
use POSIX;
use Carp;
use OSCAR::Database;

# First of all, enforce that the user running this script is 'root'

croak "You must be 'root' to run this script.  Aborting" if ($< != 0);

# Second, find the binary package format

my $adapter = shift;

if ( !system("dpkg-deb --help >/dev/null 2>/dev/null") )
  {
    oscar_log_subsection("Using Deb packages.");
    system ("./install_cluster.deb $adapter\n");
  }
else 
  {
    print("Using RPM packages\n");
    oscar_log_subsection ("./install_cluster.rpm $adapter.");
  }

