#!/usr/bin/perl

# Copyright (c) 2005, INRIA.  
#                    All rights reserved.
#
# $Id$
# 
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
 
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#   This is the oscar installation program.  It must be called with
#   one argument which is the installation network device

# Find the binary package format

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use vars qw($VERSION);
use OSCAR::Logger;
use Carp;

my $real_name = "XML-Parser";

oscar_log_section ("XML-Parser setup");
oscar_log_subsection("Checking package format...");
my $topdir = "$ENV{OSCAR_HOME}/share/prereqs/$real_name";
oscar_log_subsection("Package directory is $topdir");

if ( !system("rpm --help >/dev/null 2>/dev/null") )
  {
    print("Using RPM packages\n");
    system ("$topdir/scripts/setup.rpm\n");
  }
if ( !system("dpkg-deb --help >/dev/null 2>/dev/null") )
  {
    print("Using Deb packages\n");
    system ("$topdir/scripts/setup.deb\n");
  }

