#!/usr/bin/perl
#
# Copyright (c) 2005, INRIA.
#                         All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id$
#
# check the package format to install and setup packman-depman packages
#

use strict;
use Cwd qw(chdir cwd);

use lib cwd() . "/../lib";
use vars qw($VERSION);
use OSCAR::Logger;
use OSCAR::Distro;

my ($distn, $distv) = which_distro_server();

oscar_log_section ("Setup Perl-Tk...");
if ( $distn eq 'debian' ) {
  oscar_log_subsection ("Running setup for RPM based distro...");
  system ("$ENV{OSCAR_HOME}/share/prereqs/perl-Tk/scripts/setup.deb\n");
  }
else
  {
    oscar_log_subsection ("Running setup for Deb based distro...");
    system ("$ENV{OSCAR_HOME}/share/prereqs/perl-Tk/scripts/setup.rpm\n");
  }

