#!/bin/bash 
DEV_HD=/dev/hda
HDPARTITION=/dev/hda1
HDMOUNTPT=$1
VERSION=sarge
DEBSTATUS=testing
HASPCMCIA=yes
WANTX=yes

# mount proc
chroot $HDMOUNTPT mount -t proc proc /proc

mkdir -p $HDMOUNTPT/etc/mkinitrd
echo "MODULES=most
DELAY=0
ROOT=$HDPARTITION
UMASK=022
MKIMAGE='mkcramfs %s %s > /dev/null'
BUSYBOX=no
PKGSCRIPTS=yes
INITRD_LD_LIBRARY_PATH=\$LD_LIBRARY_PATH
" > $HDMOUNTPT/etc/mkinitrd/mkinitrd.conf
echo "do_initrd = Yes" > $HDMOUNTPT/etc/kernel-img.conf

# I don't know why we have to create such a stupid user to
# install a kernel package!
chroot $HDMOUNTPT adduser --disabled-login --disabled-password --force-badname Debian-exim

# add kernel
chroot $HDMOUNTPT apt-get update
chroot $HDMOUNTPT apt-get install kernel-image-2.6-686
chroot $HDMOUNTPT apt-get -y install discover grub

# with oscar, the boot partition is on the first partition
# so we copy the kernel and the initrd file in boot to have
# a generic config of grub
cp -f $HDMOUNTPT/vmlinuz $HDMOUNTPT/boot
cp -f $HDMOUNTPT/initrd.img $HDMOUNTPT/boot

# We need to update a config file for systemconfig
echo "  DEFAULTBOOT /boot/vmlinuz" >> $HDMOUNTPT/etc/systemconfig/systemconfig.conf

mkdir -p $HDMOUNTPT/boot/grub
echo "boot=/dev/hda
default=0
timeout=1

title Debian Testing 
  root (hd0,0)
  kernel /vmlinuz ro root=/dev/hda6 vga=769
  initrd /initrd.img
" > $HDMOUNTPT/boot/grub/menu.lst


#echo "lba32
#boot=/dev/hda
#root=/dev/hda6
#install=/boot/boot-menu.b
#map=/boot/map
#delay=2
#timeout=4
#vga=normal
#default=Linux
#image=/vmlinuz
#  label=Linux
#  read-only
#  initrd=/initrd.img
#" > $HDMOUNTPT/etc/lilo.conf

#chroot $HDMOUNTPT lilo

chroot $HDMOUNTPT umount /proc
