#!/bin/bash 
DEV_HD=/dev/hda
HDPARTITION=/dev/hda1
HDMOUNTPT=$1
VERSION=sarge
DEBSTATUS=testing
HASPCMCIA=yes
WANTX=yes

# mount proc
chroot $HDMOUNTPT mount -t proc proc /proc

mkdir -p $HDMOUNTPT/etc/mkinitrd
echo "MODULES=most
DELAY=0
ROOT=$HDPARTITION
UMASK=022
MKIMAGE='mkcramfs %s %s > /dev/null'
BUSYBOX=no
PKGSCRIPTS=yes
INITRD_LD_LIBRARY_PATH=\$LD_LIBRARY_PATH
" > $HDMOUNTPT/etc/mkinitrd/mkinitrd.conf
echo "do_initrd = Yes" > $HDMOUNTPT/etc/kernel-img.conf

# I don't know why we have to create such a stupid user to
# install a kernel package!
chroot $HDMOUNTPT adduser --disabled-login --disabled-password --force-badname Debian-exim

# add kernel
chroot $HDMOUNTPT apt-get update
chroot $HDMOUNTPT apt-get install kernel-image-2.6-686
chroot $HDMOUNTPT apt-get -y install discover grub lilo
chroot $HDMOUNTPT apt-get clean

# with oscar, the boot partition is on the first partition
# so we copy the kernel and the initrd file in boot to have
# a generic config of grub
cp -f $HDMOUNTPT/vmlinuz $HDMOUNTPT/boot
cp -f $HDMOUNTPT/initrd.img $HDMOUNTPT/boot

# We need to update a config file for systemconfig
echo "CONFIGBOOT = YES
CONFIGRD = YES

[BOOT]
	ROOTDEV = /dev/hda6
	BOOTDEV = /dev/hda1
	DEFAULTBOOT = Linux
	
[KERNEL0]
	PATH = /boot/vmlinuz
	INITRD = /boot/initrd.img
	LABEL = Linux
" > $HDMOUNTPT/etc/systemconfig/systemconfig.conf

chroot $HDMOUNTPT umount /proc
